steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'eu.gcr.io/$PROJECT_ID/audioslides-io-test:latest' ]
- name: 'docker/compose:1.18.0'
  args: [ 'run',
    '-e', 'COVERALLS_REPO_TOKEN=$_COVERALLS_REPO_TOKEN',
    '-e', 'BRANCH=$BRANCH_NAME',
    '-e', 'SHA=$SHORT_SHA',
    'test' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'eu.gcr.io/$PROJECT_ID/audioslides-io-test:latest',
    '-t', 'eu.gcr.io/$PROJECT_ID/audioslides-io-test',
    '.' ]
images:
- 'eu.gcr.io/$PROJECT_ID/audioslides-io-test'