steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'eu.gcr.io/$PROJECT_ID/audioslides-io:latest' ]
- name: 'docker/compose:1.18.0'
  args: [ 'run',
    '-e', 'MIX_ENV=test',
    '-e', 'COVERALLS_REPO_TOKEN=$_COVERALLS_REPO_TOKEN',
    'test',
    'mix', 'coveralls.post',
    '--branch', '$BRANCH_NAME',
    '--sha', '$COMMIT_SHA'
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'eu.gcr.io/$PROJECT_ID/audioslides-io:latest',
    '-t', 'eu.gcr.io/$PROJECT_ID/audioslides-io',
    '.' ]
images:
- 'eu.gcr.io/$PROJECT_ID/audioslides-io'