steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'eu.gcr.io/$PROJECT_ID/audioslides-io-test:latest' ]
- name: 'docker/compose:1.18.0'
  args: [ 'run',
    '-e', 'MIX_ENV=test'
    'test',
    'mix', 'coveralls.post',
    '--token', '"$_COVERALLS_REPO_TOKEN"',
    '--branch', '"$BRANCH_NAME"',
    '--sha', '"$COMMIT_SHA"'
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'eu.gcr.io/$PROJECT_ID/audioslides-io-test:latest',
    '-t', 'eu.gcr.io/$PROJECT_ID/audioslides-io-test',
    '.' ]
images:
- 'eu.gcr.io/$PROJECT_ID/audioslides-io-test'