steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'eu.gcr.io/$PROJECT_ID/audioslides-io-test:latest' ]
- name: 'docker/compose'
  args: [ 'run', 'test' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'eu.gcr.io/$PROJECT_ID/audioslides-io-test:latest',
    '-t', 'eu.gcr.io/$PROJECT_ID/audioslides-io-test',
    '.' ]
images:
- 'eu.gcr.io/$PROJECT_ID/audioslides-io-test'