steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg', 'MIX_ENV=test',
    '--cache-from', 'eu.gcr.io/$PROJECT_ID/audioslides-io-test-runner:latest',
    '-t', 'eu.gcr.io/$PROJECT_ID/audioslides-io-test-runner:latest',
    '.' ]
images:
- 'eu.gcr.io/$PROJECT_ID/audioslides-io-test-runner:latest'